### ISSUE TITLE
Deciding on documentation space

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#49] opened 2022-02-15 23:19 UTC
We need a central space for documenting topics of this deployment.

I would be happy to hear the team's thoughts here - what's a good, approachable place to put this?

**Comment by jchristgit** [comment] 2022-02-15 23:21
cc @jchristgit @ChrisLovering @MrHemlock @minalike what would be the most approachable spot to find documentation?

**Comment by jchristgit** [comment] 2022-02-15 23:37
Let's use markdown for this, especially with the new flowchart support.

**Comment by jchristgit** [comment] 2022-02-15 23:38
@jb3 will set this up, link and structure it accordingly.

**Comment by MarkKoz** [comment] 2022-02-16 02:04
The first thing that comes to mind is Notion. The next thing that comes to mind is static page using GH Pages (never attempted this, so I don't know how involved it is). Lastly, it could just be loose files in a directory on this repo, but that's more difficult to navigate.

**Comment by jchristgit** [comment] 2022-02-22 22:30
Hi @jb3! Any updates on this issue?

**Comment by jchristgit** [comment] 2022-02-22 23:55
> if you've got solution ideas i'm happy to have people present and we collectively decide - i just don't have a load of time right now to source those ideas myself and consider all options proportionately

**Comment by jchristgit** [comment] 2022-02-27 22:35
@ChrisLovering @imsofi would be happy to also have your input here!

The new suggestion: markdown documentation built and published using GitHub pages living in the Git repository

**Comment by ChrisLovering** [comment] 2022-02-27 22:37
Getting some markdown together will be a good start, we can push that to github pages some point after that if needed.

**Comment by ChrisLovering** [comment] 2023-08-08 19:42
Duplicate of https://github.com/python-discord/infra/issues/113

**Closed by ChrisLovering** 2023-08-08 19:42 UTC
Labels: type: doc
