### ISSUE TITLE
Unify meeting notes

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#108] opened 2023-07-18 20:41 UTC
At the moment we have a mix of meeting notes in here and in notion. Which do we prefer? We should unify our notes into that system.

**Comment by jchristgit** [comment] 2023-07-18 20:41
Personally I prefer on git due to ease of discovery and tracking, and well because it's just plain text. Curious about other thoughts

**Comment by ChrisLovering** [comment] 2023-08-08 19:42
Duplicate of https://github.com/python-discord/infra/issues/113

**Closed by ChrisLovering** 2023-08-08 19:42 UTC
