### ISSUE TITLE
Clean up Notion documentation space

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#112] opened 2023-08-02 17:03 UTC
Lots of unused things are floating around there. If they are useful, we should integrate them into git.

https://www.notion.so/pythondiscord/DevOps-45b136c23b6e41d8b08bedb892c272b3

**Comment by ChrisLovering** [comment] 2023-08-08 19:42
Duplicate of https://github.com/python-discord/infra/issues/113

**Closed by ChrisLovering** 2023-08-08 19:42 UTC
